// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// grow_forest_cpp
Rcpp::List grow_forest_cpp(Rcpp::IntegerVector Y, Rcpp::NumericMatrix X, int num_trees, int min_node_size, int max_depth, int n_sub, int mtry, int M, Rcpp::NumericVector lambda, int num_threads);
RcppExport SEXP _jocf_grow_forest_cpp(SEXP YSEXP, SEXP XSEXP, SEXP num_treesSEXP, SEXP min_node_sizeSEXP, SEXP max_depthSEXP, SEXP n_subSEXP, SEXP mtrySEXP, SEXP MSEXP, SEXP lambdaSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type num_trees(num_treesSEXP);
    Rcpp::traits::input_parameter< int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type n_sub(n_subSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(grow_forest_cpp(Y, X, num_trees, min_node_size, max_depth, n_sub, mtry, M, lambda, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// grow_forest_oob_cpp
Rcpp::List grow_forest_oob_cpp(Rcpp::IntegerVector Y, Rcpp::NumericMatrix X, int num_trees, int min_node_size, int max_depth, int n_sub, int mtry, int M, Rcpp::NumericVector lambda, int num_threads);
RcppExport SEXP _jocf_grow_forest_oob_cpp(SEXP YSEXP, SEXP XSEXP, SEXP num_treesSEXP, SEXP min_node_sizeSEXP, SEXP max_depthSEXP, SEXP n_subSEXP, SEXP mtrySEXP, SEXP MSEXP, SEXP lambdaSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type num_trees(num_treesSEXP);
    Rcpp::traits::input_parameter< int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    Rcpp::traits::input_parameter< int >::type n_sub(n_subSEXP);
    Rcpp::traits::input_parameter< int >::type mtry(mtrySEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(grow_forest_oob_cpp(Y, X, num_trees, min_node_size, max_depth, n_sub, mtry, M, lambda, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// predict_forest_cpp
Rcpp::List predict_forest_cpp(Rcpp::List forest, Rcpp::NumericMatrix X_new, int M, int num_threads);
RcppExport SEXP _jocf_predict_forest_cpp(SEXP forestSEXP, SEXP X_newSEXP, SEXP MSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_new(X_newSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_forest_cpp(forest, X_new, M, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// marginal_effects_cpp
Rcpp::NumericMatrix marginal_effects_cpp(Rcpp::List forest, Rcpp::NumericMatrix X_eval, Rcpp::IntegerVector target_vars, Rcpp::LogicalVector is_discrete, Rcpp::NumericVector h_vec, int M, int num_threads);
RcppExport SEXP _jocf_marginal_effects_cpp(SEXP forestSEXP, SEXP X_evalSEXP, SEXP target_varsSEXP, SEXP is_discreteSEXP, SEXP h_vecSEXP, SEXP MSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type forest(forestSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X_eval(X_evalSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type target_vars(target_varsSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type is_discrete(is_discreteSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type h_vec(h_vecSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(marginal_effects_cpp(forest, X_eval, target_vars, is_discrete, h_vec, M, num_threads));
    return rcpp_result_gen;
END_RCPP
}
// node_impurity_cpp
double node_impurity_cpp(Rcpp::IntegerVector counts, int n, int M, Rcpp::NumericVector lambda);
RcppExport SEXP _jocf_node_impurity_cpp(SEXP countsSEXP, SEXP nSEXP, SEXP MSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(node_impurity_cpp(counts, n, M, lambda));
    return rcpp_result_gen;
END_RCPP
}
// find_best_split_cpp
Rcpp::List find_best_split_cpp(Rcpp::IntegerVector y, Rcpp::NumericMatrix x, int M, Rcpp::NumericVector lambda, int min_node_size);
RcppExport SEXP _jocf_find_best_split_cpp(SEXP ySEXP, SEXP xSEXP, SEXP MSEXP, SEXP lambdaSEXP, SEXP min_node_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type min_node_size(min_node_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(find_best_split_cpp(y, x, M, lambda, min_node_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jocf_grow_forest_cpp", (DL_FUNC) &_jocf_grow_forest_cpp, 10},
    {"_jocf_grow_forest_oob_cpp", (DL_FUNC) &_jocf_grow_forest_oob_cpp, 10},
    {"_jocf_predict_forest_cpp", (DL_FUNC) &_jocf_predict_forest_cpp, 4},
    {"_jocf_marginal_effects_cpp", (DL_FUNC) &_jocf_marginal_effects_cpp, 7},
    {"_jocf_node_impurity_cpp", (DL_FUNC) &_jocf_node_impurity_cpp, 4},
    {"_jocf_find_best_split_cpp", (DL_FUNC) &_jocf_find_best_split_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_jocf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
