# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Grow a joint OCF random forest
#'
#' Internal C++ engine called by [jocf()].
#'
#' @param Y Integer vector of class labels (1..M), length n.
#' @param X Numeric matrix of covariates (n x k).
#' @param num_trees Number of trees.
#' @param min_node_size Minimum observations per terminal node.
#' @param mtry Number of candidate features at each split.
#' @param M Number of outcome classes.
#' @param lambda Numeric weight vector of length M.
#' @param num_threads Number of OpenMP threads (0 = all available).
#'
#' @return Named list: `predictions` (n x M) and `forest` (list of B trees).
#' @keywords internal
#' @export
grow_forest_cpp <- function(Y, X, num_trees, min_node_size, mtry, M, lambda, num_threads = 0L) {
    .Call(`_jocf_grow_forest_cpp`, Y, X, num_trees, min_node_size, mtry, M, lambda, num_threads)
}

#' Predict class probabilities from a fitted jocf forest
#'
#' Internal C++ engine called by [predict.jocf()].
#'
#' @param forest List of tree structures (from `grow_forest_cpp`).
#' @param X_new Numeric matrix of new observations (n_test x k).
#' @param M Number of outcome classes.
#' @param num_threads Number of OpenMP threads (0 = all available).
#'
#' @return Numeric matrix (n_test x M) of predicted class probabilities.
#' @keywords internal
#' @export
predict_forest_cpp <- function(forest, X_new, M, num_threads = 0L) {
    .Call(`_jocf_predict_forest_cpp`, forest, X_new, M, num_threads)
}

#' Compute average marginal effects from a fitted jocf forest
#'
#' Internal C++ engine called by [marginal_effects.jocf()].
#'
#' @param forest List of tree structures (from `grow_forest_cpp`).
#' @param X_eval Numeric matrix of evaluation points (n_eval x k).
#' @param target_vars Integer vector of 0-based column indices to differentiate.
#' @param is_discrete Logical vector (length k_target); TRUE = discrete covariate.
#' @param h_vec Numeric vector (length k_target); step size omega*sd_j for
#'   continuous variables (ignored for discrete).
#' @param M Number of outcome classes.
#' @param num_threads Number of OpenMP threads (0 = all available).
#'
#' @return Numeric matrix (k_target x M) of average marginal effects.
#' @keywords internal
#' @export
marginal_effects_cpp <- function(forest, X_eval, target_vars, is_discrete, h_vec, M, num_threads = 0L) {
    .Call(`_jocf_marginal_effects_cpp`, forest, X_eval, target_vars, is_discrete, h_vec, M, num_threads)
}

#' Compute node impurity Q(C) or Q_w(C)
#'
#' Given class-frequency counts for a node, computes the (weighted) average
#' Gini impurity:
#' \deqn{Q(C) = \frac{1}{M} \sum_{m=1}^{M} \lambda_m \,
#'        \check{p}_m(C)\,(1-\check{p}_m(C))}
#' where \eqn{\check{p}_m(C) = \texttt{counts}[m] / n}.
#' Pass `lambda = rep(1, M)` for the unweighted criterion.
#'
#' @param counts Integer vector of class counts (length M).
#' @param n Total observations in the node.
#' @param M Number of outcome classes.
#' @param lambda Numeric weight vector of length M.
#'
#' @return Scalar node impurity.
#' @keywords internal
#' @export
node_impurity_cpp <- function(counts, n, M, lambda) {
    .Call(`_jocf_node_impurity_cpp`, counts, n, M, lambda)
}

#' Find the best split for a node
#'
#' Exhaustively searches all features and candidate thresholds for the split
#' that minimises `Q(left) + Q(right)`.  Ties in feature values are skipped
#' (no split between identical values).
#'
#' @param y Integer vector of class labels (1..M); length = node size.
#' @param x Numeric matrix of covariates for node observations (node_size x k).
#' @param M Number of outcome classes.
#' @param lambda Numeric weight vector of length M.
#' @param min_node_size Minimum number of observations in each child node.
#'
#' @return A named list with elements `feature` (1-based integer), `threshold`
#'   (numeric), `impurity` (numeric), and `found` (logical).
#' @keywords internal
#' @export
find_best_split_cpp <- function(y, x, M, lambda, min_node_size) {
    .Call(`_jocf_find_best_split_cpp`, y, x, M, lambda, min_node_size)
}

